---
  - name: Ensure plugin directory exists
    file: path="{{callback_plugin_dest}}" state=directory

  - name: Ensure foreman_callback.py is present
    get_url:
      url: "{{callback_plugin_url}}"
      dest: "{{callback_plugin_dest}}"

  - name: Ensure ansible ppa repo is present
    apt_repository: repo="ppa:ansible/ansible" updsate_cache=yes

  - name: Ensure ansible is installed
    apt: name=ansible state=present

  - name: Ensure rubygem foreman ansible is installed
    apt: name=rubygem-foreman_ansible state=present
