---
  - name: Setup and configure foreman
    hosts: controller
    gather_facts: True
    connection: local
    become: yes
    roles:
      - foreman
      - salt
      - foreman_salt
      - foreman_ansible
