---
  - name: Setup and configure foreman
    hosts: controller
    gather_facts: True
    connection: local
    become: yes
    roles:
      #- foreman
      #- webserver
      - salt
      #- foreman_salt
