---
  - include: users.yml
  
  - name: Ensure key for saltstack is present
    apt_key: url="https://repo.saltstack.com/apt/ubuntu/{{ansible_distribution_version}}/amd64/latest/SALTSTACK-GPG-KEY.pub" state=present


  - name: Ensure saltstack repo present
    apt_repository: repo="deb http://repo.saltstack.com/apt/ubuntu/{{ansible_distribution_version}}/amd64/latest {{ansible_distribution_release}} main" filename="saltstack.list" state=present

  - name: Ensure salt-master is installed
    apt: name=salt-master

  - name: Ensure salt-minion is installed

    apt: name=salt-minion

  - name: Ensure salt-api is installed
    apt: name=salt-api

  - name: Ensure salt-cloud is installed
    apt: name=salt-cloud

  - name: Ensure openssl is installed
    apt: name=openssl

  - name: Ensure ssl directory exists
    file:
      path: "{{ssl_dir}}"
      state: directory

  - name: Generated ssl key and certificate
    shell: openssl req -new -newkey rsa:4096 -days 3650  -nodes -x509 -subj "/C=NO/ST=Hordaland/L=Bergen/O=Dis/CN=www.tull.no" -keyout "{{ssl_dir}}/{{ssl_key}}"  -out "{{ssl_dir}}/{{ssl_cert}}"

  - name: Configure salt-minion
    template: src="minion.j2" dest="{{minion_config_file}}"

  - name: Configure salt-api
    template: src="api.conf.j2" dest="{{master_config_folder}}/api.conf"

  - name: Restart salt-minion service
    service:
      enabled: yes
      name: salt-minion
      state: restarted

  - name: Restart salt-master service
    service:
      enabled: yes
      name: salt-master
      state: restarted
