---
  - name: Add salt-api group
    group:
      name: "{{api_user}}"
      state: present

  - name: Add salt-api user
    user:
      createhome: yes
      name: "{{api_user}}"
      group: "{{api_user}}"
      password: "{{api_user_pass}}"
      state: present
