---
  - name: Ensure autosign.conf file is present
    file:
      path: "{{autosign_file}}"
      group: foreman-proxy
      state: touch
      mode:
        0770

  - name: Add salt-master config for foreman
    template: src="master.j2" dest="{{master_config_folder}}/master.conf"

  - name: Add foreman.yaml to saltstack
    file: src="{{puppet_foreman_yml}}" path="{{salt_folder}}/foreman.yaml" state=link force=yes group=foreman-proxy
    register: foreman_yaml_facts
  - debug: msg="{{foreman_yaml_facts}}"

  - name: Add salt.yml to foreman-proxy
    template: src="salt.j2" dest="{{foreman_salt_config_file}}"

  - name: Restart salt-master to trigger new configuration
    service: enabled=yes name=salt-master state=restarted

  - name: Restart salt-api to trigger new configuration
    service: enabled=yes name=salt-master state=restarted

  - name: Restart foreman to trigger new configuration
    service: enabled=yes name=foreman state=restarted

  - name: Restart foreman-proxy to trigger new configuration
    service: enabled=yes name=foreman-proxy state=restarted
