---
  - name: Ensure nginx is installed
    apt: name="nginx" state=present

  - name: Copy foreman nginx configure
    template: src="foreman.nginx.j2" dest="{{nginx_sites-available}}/{{nginx_foreman_file}}"

  - name: Remove default nginx sites links
    file:
      path: "{{nginx_sites-available}}/default"
      state: absent

  - name: Remove default nginx sites
    file:
      path: "{{nginx_sites-enabled}}/default"
      state: absent

  - name: Enable foreman site
    file:
      src: "{{nginx_sites-available}}/{{nginx_foreman_file}}"
      dest: "{{nginx_sites-enabled}}/{{nginx_foreman_file}}"

  - name: Restart nginx with new config
    service:
      enabled: yes
      name: nginx
      state: restarted
